# Generated by Django 5.2.8 on 2025-11-26 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('icon', models.CharField(help_text='Название иконки или emoji', max_length=50, verbose_name='Иконка')),
                ('xp_reward', models.IntegerField(default=100, verbose_name='Награда XP')),
                ('condition', models.JSONField(help_text='Логика получения в формате JSON', verbose_name='Условие получения')),
            ],
        ),
        migrations.AlterModelOptions(
            name='courselesson',
            options={'ordering': ['order'], 'verbose_name': 'Lesson', 'verbose_name_plural': 'Lessons'},
        ),
        migrations.AlterModelOptions(
            name='coursemodule',
            options={'ordering': ['order'], 'verbose_name': 'Module', 'verbose_name_plural': 'Modules'},
        ),
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
        migrations.AddField(
            model_name='course',
            name='parsed_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Данные анализа'),
        ),
        migrations.AddField(
            model_name='course',
            name='source_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на Stepik'),
        ),
        migrations.AddField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='courselesson',
            name='key_concepts',
            field=models.JSONField(default=list, verbose_name='Ключевые концепции'),
        ),
        migrations.AddField(
            model_name='coursemodule',
            name='complexity',
            field=models.CharField(choices=[('beginner', 'Начинающий'), ('intermediate', 'Средний'), ('advanced', 'Продвинутый')], default='beginner', max_length=15, verbose_name='Сложность'),
        ),
        migrations.AddField(
            model_name='coursemodule',
            name='estimated_hours',
            field=models.FloatField(default=2.0, verbose_name='Часов на изучение'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='courselesson',
            name='content',
            field=models.TextField(blank=True, verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='courselesson',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='courselesson',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='coursemodule',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='coursemodule',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_data', models.JSONField(verbose_name='Данные стратегии')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активный'), ('completed', 'Завершен'), ('paused', 'Приостановлен')], default='draft', max_length=10, verbose_name='Статус')),
                ('total_xp', models.IntegerField(default=0, verbose_name='Всего XP')),
                ('current_level', models.IntegerField(default=1, verbose_name='Текущий уровень')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_plans', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Study Plan',
                'verbose_name_plural': 'Study Plans',
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_style', models.CharField(choices=[('visual', 'Визуал'), ('auditory', 'Аудиал'), ('kinesthetic', 'Кинестет'), ('reading', 'Чтение/Письмо')], max_length=20, verbose_name='Стиль обучения')),
                ('discipline_level', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], max_length=10, verbose_name='Уровень самодисциплины')),
                ('memory_capacity', models.CharField(choices=[('low', 'Низкая'), ('medium', 'Средняя'), ('high', 'Высокая')], default='medium', max_length=10, verbose_name='Объем памяти')),
                ('weekly_hours', models.IntegerField(default=5, verbose_name='Часов в неделю')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False, verbose_name='Завершено')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершено в')),
                ('xp_earned', models.IntegerField(default=0, verbose_name='Заработано XP')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='courses.courselesson')),
                ('study_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='courses.studyplan')),
            ],
            options={
                'verbose_name': 'Study Progress',
                'verbose_name_plural': 'Study Progress Records',
                'unique_together': {('study_plan', 'lesson')},
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.achievement')),
                ('study_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.studyplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'achievement')},
            },
        ),
    ]
