# Generated by Django 5.2.8 on 2025-11-26 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_achievement_alter_courselesson_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CognitiveTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('learning_style', 'Стиль обучения'), ('memory', 'Память'), ('discipline', 'Самодисциплина')], max_length=20, verbose_name='Раздел')),
                ('question_number', models.IntegerField(verbose_name='Номер вопроса')),
                ('question_text', models.TextField(verbose_name='Текст вопроса')),
                ('option_a', models.CharField(max_length=200, verbose_name='Вариант A')),
                ('option_b', models.CharField(max_length=200, verbose_name='Вариант B')),
                ('option_c', models.CharField(max_length=200, verbose_name='Вариант C')),
                ('option_d', models.CharField(max_length=200, verbose_name='Вариант D')),
            ],
            options={
                'ordering': ['section', 'question_number'],
                'unique_together': {('section', 'question_number')},
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_style', models.CharField(choices=[('visual', 'Визуал'), ('auditory', 'Аудиал'), ('reading', 'Чтение/Письмо'), ('kinesthetic', 'Кинестет'), ('mixed', 'Смешанный')], max_length=20, verbose_name='Стиль обучения')),
                ('memory_score', models.IntegerField(verbose_name='Оценка памяти (1-10)')),
                ('discipline_score', models.IntegerField(verbose_name='Оценка самодисциплины (1-10)')),
                ('raw_answers', models.JSONField(verbose_name='Сырые ответы')),
                ('calculated_scores', models.JSONField(verbose_name='Рассчитанные баллы')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
